
all:
	cd ./projects/access_test && $(MAKE)
	cd ./projects/interval_test && $(MAKE)	
	cd ./projects/interval_math && $(MAKE)		
	cd ./projects/pool_test && $(MAKE)
	
clean:
	cd ./projects/access_test && $(MAKE) clean
	cd ./projects/interval_test && $(MAKE) clean
	cd ./projects/interval_math && $(MAKE) clean	
	cd ./projects/pool_test && $(MAKE) clean
			